// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvjAKezSDR61KLfJCtqsgXc944nJaRRrA',
    appId: '1:823642880461:android:d5dffc580f8b52bd2e6c84',
    messagingSenderId: '823642880461',
    projectId: 'flutterfire-23423',
    storageBucket: 'flutterfire-23423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIvuBAi-mqvI8-3bjvD8dEf-ecSXxI2aU',
    appId: '1:823642880461:ios:5321ff2b7c2d3a992e6c84',
    messagingSenderId: '823642880461',
    projectId: 'flutterfire-23423',
    storageBucket: 'flutterfire-23423.firebasestorage.app',
    androidClientId: '823642880461-l2059kl7j7mb68dtanaei2k4ft040sql.apps.googleusercontent.com',
    iosClientId: '823642880461-6at6i9ci0imb356l0ur5lgruptngr66u.apps.googleusercontent.com',
    iosBundleId: 'com.kmtemp.social.login.app',
  );

}